name: Black Code Formatter

on:
  push:
    branches: [ "i190534" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python Env
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: pip install black

      - name: Run Black
        run: black .
