name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou master, dependendo da sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # ou a versão que você usa

      - name: Install dependencies
        run: |
          cd docs-site 
          npm ci        

      - name: Build
        run: |
          cd docs-site  
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs-site/out  # pasta gerada pela build do Next.js dentro do diretório docs-site
          branch: gh-pages       # branch onde será publicado