name: Run YAKE Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        id: run-tests
        run: |
          pytest -v tests/test_yake.py | tee test_output.log

      - name: Verify test results
        run: |
          if grep -q '6 passed' test_output.log; then
            echo "✅ Todos os testes passaram com sucesso!"
            exit 0
          else
            echo "❌ Alguns testes falharam! Verifique o log para mais detalhes."
            exit 1

      - name: Upload test results (em caso de falha)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test_output.log
